# Generated by Django 3.0.3 on 2020-08-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sirket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_adi', models.CharField(max_length=50, null=True, verbose_name='Şirket Adı')),
                ('sirket_adresi', models.CharField(default='', max_length=150, verbose_name='Şirket Adresi')),
                ('sirket_no', models.CharField(max_length=20, verbose_name='Şirket No')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
