# Generated by Django 3.0.3 on 2020-08-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirket',
            name='created_date',
            field=models.DateTimeField(null=True, verbose_name='Oluşturulma Tarihi'),
        ),
    ]
