# Generated by Django 3.0.3 on 2020-08-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirketapp', '0010_auto_20200823_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirket',
            name='created_time',
            field=models.TimeField(null=True, verbose_name='Oluşturulma Zamani'),
        ),
    ]
