# Generated by Django 3.0.3 on 2020-08-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirketapp', '0011_sirket_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirket',
            name='created_date2',
            field=models.DateTimeField(null=True, verbose_name='Oluşturulma Tarihi2'),
        ),
    ]
