# Generated by Django 3.0.3 on 2020-09-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirketapp', '0013_auto_20200823_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirket',
            name='arac_model',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Araç Modeli'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='arac_plaka',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Araç Plaka'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='sofor_adi',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Şöför Adı'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='sofor_tel_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Şöför Telefon No'),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_adi',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Şirket Adı'),
        ),
    ]
