# Generated by Django 3.0.3 on 2020-09-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirketapp', '0019_auto_20200912_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirket',
            name='calisan_TC_NO',
            field=models.CharField(max_length=12, null=True, verbose_name='Çalışan TC NO'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='calisan_adi',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Çalışan Adı'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='calisan_ev_adresi',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Çalışan Ev Adresi'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='calisan_is_adresi',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Çalışan İş Adresi'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='calisan_soyad',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Çalışan Soyadı'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='calisan_tel_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Çalışan Telefon No'),
        ),
    ]
