# Generated by Django 3.0.3 on 2020-09-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirketapp', '0020_auto_20200922_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='SirketCalisan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calisan_adi', models.CharField(blank=True, default='', max_length=50, verbose_name='Çalışan Adı')),
                ('calisan_soyad', models.CharField(blank=True, default='', max_length=50, verbose_name='Çalışan Soyadı')),
                ('calisan_TC_NO', models.CharField(max_length=12, null=True, verbose_name='Çalışan TC NO')),
                ('calisan_ev_adresi', models.CharField(blank=True, default='', max_length=150, verbose_name='Çalışan Ev Adresi')),
                ('calisan_is_adresi', models.CharField(blank=True, default='', max_length=150, verbose_name='Çalışan İş Adresi')),
                ('calisan_tel_no', models.CharField(blank=True, default='', max_length=20, verbose_name='Çalışan Telefon No')),
                ('created_date', models.DateTimeField(null=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.RemoveField(
            model_name='sirket',
            name='calisan_TC_NO',
        ),
        migrations.RemoveField(
            model_name='sirket',
            name='calisan_adi',
        ),
        migrations.RemoveField(
            model_name='sirket',
            name='calisan_ev_adresi',
        ),
        migrations.RemoveField(
            model_name='sirket',
            name='calisan_is_adresi',
        ),
        migrations.RemoveField(
            model_name='sirket',
            name='calisan_soyad',
        ),
        migrations.RemoveField(
            model_name='sirket',
            name='calisan_tel_no',
        ),
    ]
