# Generated by Django 3.0.3 on 2020-08-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteriapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
    ]
