# Generated by Django 3.0.3 on 2020-09-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteriapp', '0002_auto_20200814_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri',
            name='TC_NO',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='TC NO'),
        ),
        migrations.AddField(
            model_name='musteri',
            name='ucus_kodu',
            field=models.CharField(max_length=50, null=True, verbose_name='Ucuş Kodu'),
        ),
    ]
