# Generated by Django 3.0.3 on 2020-09-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteriapp', '0004_auto_20200908_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='TC_NO',
            field=models.CharField(max_length=12, null=True, verbose_name='TC NO'),
        ),
    ]
