# Generated by Django 3.0.3 on 2020-09-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteriapp', '0007_auto_20200910_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='created_date',
            field=models.DateTimeField(null=True, verbose_name='Oluşturulma Tarihi'),
        ),
    ]
