# Generated by Django 3.0.3 on 2020-09-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musteriapp', '0008_auto_20200910_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musteri',
            old_name='ad',
            new_name='adi',
        ),
    ]
