# Generated by Django 3.0.3 on 2020-09-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteriapp', '0009_auto_20200910_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri',
            name='alindigi_adres',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Alındığı Adres'),
        ),
        migrations.AddField(
            model_name='musteri',
            name='birakildigi_adres',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Bırakıldığı Adres'),
        ),
    ]
