# Generated by Django 3.0.3 on 2020-09-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteriapp', '0013_auto_20200911_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri',
            name='birakildigi_ev_adresi',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Ev Adresi'),
        ),
        migrations.AddField(
            model_name='musteri',
            name='birakildigi_is_adresi',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Ev Adresi'),
        ),
    ]
