# Generated by Django 3.0.3 on 2020-09-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musteriapp', '0014_auto_20200911_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musteri',
            options={'ordering': ['adi']},
        ),
    ]
