# Generated by Django 3.0.3 on 2020-09-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteriapp', '0015_auto_20200913_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='tel_no',
            field=models.CharField(max_length=20, null=True, verbose_name='Telefon No'),
        ),
    ]
