# Generated by Django 3.0.3 on 2020-09-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AracSofor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sofor_adi', models.CharField(blank=True, default='', max_length=50, verbose_name='Şöför Adı')),
                ('sofor_tel_no', models.CharField(blank=True, default='', max_length=20, verbose_name='Şöför Telefon No')),
                ('arac_model', models.CharField(blank=True, default='', max_length=50, verbose_name='Araç Modeli')),
                ('arac_plaka', models.CharField(blank=True, default='', max_length=50, verbose_name='Araç Plaka')),
                ('created_date', models.DateTimeField(null=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
