# Generated by Django 3.0.3 on 2020-09-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aracsoforapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AracModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arac_model', models.CharField(blank=True, default='', max_length=50, verbose_name='Araç Modeli')),
                ('arac_plaka', models.CharField(blank=True, default='', max_length=50, verbose_name='Araç Plaka')),
                ('created_date', models.DateTimeField(null=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
