# Generated by Django 3.0.3 on 2020-09-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aracsoforapp', '0002_aracmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aracsofor',
            name='arac_model',
        ),
        migrations.RemoveField(
            model_name='aracsofor',
            name='arac_plaka',
        ),
    ]
