# Generated by Django 3.0.3 on 2020-09-11 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aracsoforapp', '0003_auto_20200910_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aracmodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='aracsofor',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
    ]
