# Generated by Django 3.0.3 on 2020-07-26 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_adi', models.CharField(max_length=50, verbose_name='Şirket Adı')),
                ('tel_no', models.CharField(max_length=20, verbose_name='Telefon No')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_tarihi', models.DateTimeField(verbose_name='date created')),
                ('transfer_ucreti', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('yolcu_ismi', models.CharField(max_length=50, verbose_name='Yolcu Ismi')),
                ('sirket_bilgisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sirket_bilgisi', to='transferapp.UserProfile', verbose_name='Sirket Bilgisi')),
            ],
            options={
                'ordering': ['-transfer_tarihi'],
            },
        ),
    ]
