# Generated by Django 3.0.3 on 2020-07-28 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transferapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='yolcu_ismi',
            field=models.CharField(max_length=50, verbose_name='Oyuncu Ismi'),
        ),
    ]
