# Generated by Django 3.0.3 on 2020-07-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('transferapp', '0002_auto_20200728_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='sirket_bilgisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sirket_bilgisi', to='user.UserProfile', verbose_name='Sirket Bilgisi'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
