# Generated by Django 3.0.3 on 2020-08-03 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200804_0043'),
        ('transferapp', '0004_auto_20200803_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='ev_adresi',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Ev Adresi'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sirket_bilgisi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sirket_bilgisi', to='user.UserProfile', verbose_name='Şirket Bilgisi'),
        ),
    ]
