# Generated by Django 3.0.3 on 2020-08-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200804_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sirket_adi',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tel_no',
        ),
    ]
